const colors = [
  "Red",
  "Green",
  "Blue",
  "Yellow",
  "Purple",
  "Orange",
  "Pink",
  "Brown",
  "Cyan",
  "Magenta",
  "Lime",
  "Teal",
  "Indigo",
  "Violet",
  "Aqua",
  "Turquoise",
  "Olive",
  "Maroon",
  "Navy",
  "Silver",
  "Gray",
  "Black",
  "White",
  "Gold",
  "Silver",
  "Beige",
  "Lavender",
  "Salmon",
  "Turquoise",
  "SlateGray",
  "Sienna",
  "Peru",
  "Tomato",
  "SkyBlue",
  "LemonChiffon",
  "PapayaWhip",
  "SeaGreen",
  "Orchid",
  "RoyalBlue",
  "SaddleBrown",
  "SlateBlue",
  "MediumPurple",
  "PowderBlue",
  "FireBrick",
  "DarkOliveGreen",
  "DeepSkyBlue",
  "DarkGoldenRod",
  "CadetBlue",
  "Crimson",
  "MediumAquaMarine",
  "MediumSeaGreen",
  "MediumVioletRed",
  "DarkOrchid",
  "DarkSlateGray",
  "Chocolate",
  "DarkSalmon",
  "MediumOrchid",
  "DarkTurquoise",
  "LightSeaGreen",
  "LightSlateGray",
  "LightSteelBlue",
  "MediumSlateBlue",
  "MidnightBlue",
  "OliveDrab",
  "SandyBrown",
  "YellowGreen",
  "PaleVioletRed",
  "Plum",
  "RosyBrown",
  "DarkKhaki",
  "DeepPink",
  "HotPink",
  "IndianRed",
  "LightCoral",
  "LightPink",
  "LightSalmon",
  "LightSkyBlue",
  "PaleGoldenRod",
  "PaleGreen",
  "PaleTurquoise",
  "LightGray",
  "LightGreen",
  "LightYellow",
  "Thistle",
  "Wheat",
  "rgba(133,122,200)",
  "#f15025",
];
const btn = document.getElementById("btn");
const color = document.querySelector(".color");

btn.addEventListener("click", function () {
  const randomNumber = getRandomNumber();
  // console.log(randomNumber);

  document.querySelector(".left").style.backgroundColor = colors[randomNumber];
  color.textContent = colors[randomNumber];
});

function getRandomNumber() {
  return Math.floor(Math.random() * colors.length);
}
